version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  top.api:
    image: ghcr.io/leagermaxl/nest-top-api/top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
