volumes:
  mongo-data:

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
